# Copyright (c) Facebook, Inc. and its affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import torch
import torch.nn as nn
import torch.nn.functional as F

# In EGG, the game designer must implement the core functionality of the Sender and Receiver agents. These are then
# embedded in wrappers that are used to train them to play Gumbel-Softmax- or Reinforce-optimized games. The core
# Sender must take the input and produce a hidden representation that is then used by the wrapper to initialize
# the RNN or other module that will generate the message. The core Receiver expects a hidden representation
# generated by the message-processing wrapper, plus possibly other game-specific input, and it must generate the
# game-specific output.

# The RecoReceiver class implements the core Receiver agent for the reconstruction game. This is simply a linear layer
# that takes as input the vector generated by the message-decoding RNN in the wrapper (x in the forward method) and
# produces an output of n_features dimensionality, to be interpreted as a one-hot representation of the reconstructed
# attribute-value vector
class RecoReceiver(nn.Module):
    def __init__(self, n_features, n_hidden):
        super(RecoReceiver, self).__init__()
        self.output = nn.Linear(n_hidden, n_features)

    def forward(self, x, _input, _aux_input):
        return self.output(x)


# The DiscriReceiver class implements the core Receiver agent for the discrimination game. In this case, besides the
# vector generated by the message-decoding RNN in the wrapper (x in the forward method), the module also gets game-specific
# Receiver input (_input), that is, the matrix containing all input attribute-value vectors. The module maps these vectors to the
# same dimensionality as the RNN output vector, and computes a dot product between the latter and each of the (transformed) input vectors.
# The output dot prodoct list is interpreted as a non-normalized probability distribution over possible positions of the target.
class DiscriReceiver(nn.Module):
    def __init__(self, n_features, n_hidden):
        super(DiscriReceiver, self).__init__()
        self.fc1 = nn.Linear(n_features, n_hidden)

    def forward(self, x, _input, _aux_input):
        # the rationale for the non-linearity here is that the RNN output will also be the outcome of a non-linearity
        embedded_input = self.fc1(_input).tanh()
        dots = torch.matmul(embedded_input, torch.unsqueeze(x, dim=-1))
        return dots.squeeze()


# The Sender class implements the core Sender agent common to both games: it gets the input target vector and produces a hidden layer
# that will initialize the message producing RNN
class Sender(nn.Module):
    def __init__(self, n_hidden, n_features):
        super(Sender, self).__init__()
        self.fc1 = nn.Linear(n_features, n_hidden)

    def forward(self, x, _aux_input):
        return self.fc1(x)
        # here, it might make sense to add a non-linearity, such as tanh


# The MNISTSender and MNISTReceiver classes are similar to the above, but adapted to the MNIST data format
# We use a convolutional neural network to process the input images in the Sender
class MNISTSender(nn.Module):
    def __init__(self, n_hidden):
        super(MNISTSender, self).__init__()
        
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        # After conv1 (28->26), pool (26->13), conv2 (13->11), pool (11->5): 64 * 5 * 5 = 1600
        self.fc1 = nn.Linear(64 * 5 * 5, 128)
        self.fc2 = nn.Linear(128, n_hidden)
    
    def forward(self, x, _aux_input):
        
        x = x.view(-1, 1, 28, 28)  # Reshape input to image format
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)
        x = x.view(x.size(0), -1)  # Flatten: (batch, 64*5*5)
        x = F.relu(self.fc1(x))
        return self.fc2(x)
    
class MNISTDiscriReceiver(nn.Module):
    def __init__(self, n_hidden):
        super(MNISTDiscriReceiver, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 64, 3, 1)
        # After conv1 (28->26), pool (26->13), conv2 (13->11), pool (11->5): 64 * 5 * 5 = 1600
        self.fc1 = nn.Linear(64 * 5 * 5, n_hidden)
        
    def forward(self, x, receiver_input, _aux_input):
        
        batch_size, n_images, img_size = receiver_input.shape
        
        # Process all images through CNN
        imgs = receiver_input.view(-1, 1, 28, 28)  # (batch*n_images, 1, 28, 28)
        imgs = F.relu(self.conv1(imgs))
        imgs = F.max_pool2d(imgs, 2)
        imgs = F.relu(self.conv2(imgs))
        imgs = F.max_pool2d(imgs, 2)
        imgs = imgs.view(batch_size, n_images, -1)  # (batch, n_images, 64*5*5)
        imgs = self.fc1(imgs).tanh()  # (batch, n_images, n_hidden)
        
        # Dot product between message encoding (x) and each image encoding
        x = x.unsqueeze(-1)  # (batch, n_hidden, 1)
        dots = torch.matmul(imgs, x).squeeze(-1)  # (batch, n_images)

        return dots
